---
services:
    doplarr:
        image: lscr.io/linuxserver/doplarr:latest
        container_name: doplarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - DISCORD__TOKEN=${DISCORD_TOKEN}
            - OVERSEERR__API=${OVERSEERR_API_KEY}
            - OVERSEERR__URL=${OVERSEERR_URL}
            - RADARR__API==${RADARR_KEY}
            - RADARR__URL==${RADARR_URL}
            - SONARR__API=${SONARR_KEY}
            - SONARR__URL=${SONARR_URL}
            # - DISCORD__MAX_RESULTS=25 #optional
            # - DISCORD__REQUESTED_MSG_STYLE=:plain #optional
            # - SONARR__QUALITY_PROFILE= #optional
            # - RADARR__QUALITY_PROFILE= #optional
            # - SONARR__ROOTFOLDER= #optional
            # - RADARR__ROOTFOLDER= #optional
            # - SONARR__LANGUAGE_PROFILE= #optional
            # - OVERSEERR__DEFAULT_ID= #optional
            # - PARTIAL_SEASONS=true #optional
            # - LOG_LEVEL=:info #optional
            # - JAVA_OPTS= #optional
        volumes:
            - ${DOCKER_CONFIG_BASE}/Doplarr-Config:/config
        networks:
            - proxy_network
        restart: unless-stopped
