services:
    filebrowser:
        image: hurlenko/filebrowser:${FILEBROWSER_VERSION}
        container_name: filebrowser
        user: "${PUID}:${PGID}"
        # command: ["--noauth", "--database", "/config/filebrowser.db"] # Authentication by authentik
        volumes:
            - ${HOST_MNT_PATH}:/data/mnt
            - ${HOST_HOME_PATH}:/data/home
            - ${DOCKER_CONFIG_BASE}/FileBrowser_Config:/config
        labels:
            - "glance.name=File Browser"
            - "glance.icon=sh:file-browser"
            - "glance.url=http://file.${BASE_DOMAIN}/"
            - "glance.description=File browser"
        networks:
            - proxy_network
        restart: always
