services:
    gitea:
        image: gitea/gitea:latest
        container_name: gitea-server
        logging:
            driver: loki:latest
            options:
                loki-url: ${LOKI_URL}
                loki-retries: 5
                loki-max-backoff: 1800ms
                loki-timeout: 1s
                keep-file: "true"
                mode: "non-blocking"
        environment:
            - USER_UID=${PUID}
            - USER_GID=${PGID}
        labels:
            - "glance.name=Gitea"
            - "glance.icon=sh:gitea"
            - "glance.url=http://gitea.${BASE_DOMAIN}/"
            - "glance.description=Version Control"
            - "glance.id=gitea"
        volumes:
            - ${DOCKER_CONFIG_BASE}/Gitea_Config/data:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - proxy_network
        ports:
            #     - "3000:3000"
            - "222:22"
        restart: unless-stopped
