services:
    huntarr:
        image: huntarr/huntarr:latest
        container_name: huntarr
        restart: always
        networks:
            - proxy_network
        # ports:
        #     - "9705:9705"
        volumes:
            - ${DOCKER_CONFIG_BASE}/Huntarr_Config:/config
        labels:
            - "glance.name=Huntarr"
            - "glance.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/huntarr.png"
            - "glance.url=http://huntarr.${BASE_DOMAIN}/"
            - "glance.description=Missing & Upgrade Media"
        environment:
            - TZ=${TZ}
