#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
    immich-server:
        container_name: immich_server
        image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
        # extends:
        #     file: ../common/immich/hwaccel.transcoding.yml
        #     service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
        logging:
            driver: loki:latest
            options:
                loki-url: ${LOKI_URL}
                loki-retries: 5
                loki-max-backoff: 1800ms
                loki-timeout: 1s
                keep-file: "true"
                mode: "non-blocking"
        environment:
            - REDIS_HOSTNAME=immich_redis
            - DB_HOSTNAME=immich_postgres
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_USERNAME=${DB_USERNAME}
            - DB_DATABASE_NAME=${DB_DATABASE_NAME}
        labels:
            # - "com.centurylinklabs.watchtower.enable=false"
            - "glance.name=immich"
            - "glance.icon=sh:immich"
            - "glance.url=http://immich.${BASE_DOMAIN}/"
            - "glance.description=Photo Backup"
            - "glance.id=immich"
        volumes:
            # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
            - ${UPLOAD_LOCATION}:/usr/src/app/upload
            - /etc/localtime:/etc/localtime:ro
        networks:
            - proxy_network
        # ports:
        #     - "2283:2283"
        depends_on:
            - immich-redis
            - immich-postgres
        restart: always
        healthcheck:
            disable: false

    immich-machine-learning:
        container_name: immich_machine_learning
        # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
        # Example tag: ${IMMICH_VERSION:-release}-cuda
        logging:
            driver: loki:latest
            options:
                loki-url: ${LOKI_URL}
                loki-retries: 5
                loki-max-backoff: 1800ms
                loki-timeout: 1s
                keep-file: "true"
                mode: "non-blocking"
        labels:
            # - "com.centurylinklabs.watchtower.enable=false"
            - "glance.parent=immich"
            - "glance.name=machine-learning"
        image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
        # extends:
        #     file: ../common/immich/hwaccel.transcoding.yml
        #     service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
        volumes:
            - model-cache:/cache
        restart: always
        networks:
            - proxy_network
        healthcheck:
            disable: false

    immich-redis:
        container_name: immich_redis
        logging:
            driver: loki:latest
            options:
                loki-url: ${LOKI_URL}
                loki-retries: 5
                loki-max-backoff: 1800ms
                loki-timeout: 1s
                keep-file: "true"
                mode: "non-blocking"
        labels:
            - "com.centurylinklabs.watchtower.enable=false"
            - "glance.parent=immich"
            - "glance.name=redis"
        image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
        healthcheck:
            test: redis-cli ping || exit 1
        restart: always
        networks:
            - proxy_network

    immich-postgres:
        container_name: immich_postgres
        image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE_NAME}
            POSTGRES_INITDB_ARGS: "--data-checksums"
            # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
            # DB_STORAGE_TYPE: 'HDD'
        labels:
            # - "com.centurylinklabs.watchtower.enable=false"
            - "glance.parent=immich"
            - "glance.name=postgres"
        logging:
            driver: loki:latest
            options:
                loki-url: ${LOKI_URL}
                loki-retries: 5
                loki-max-backoff: 1800ms
                loki-timeout: 1s
                keep-file: "true"
                mode: "non-blocking"
        networks:
            - proxy_network
        volumes:
            # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
            - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
        shm_size: 128mb
        restart: always

volumes:
    model-cache:
