services:
  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    # ports:
    #     - 6868:6868
    volumes:
      - ${DOCKER_CONFIG_BASE}/Profilarr_Docker:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - "glance.name=Profilarr"
      - "glance.icon=sh:profilarr"
      - "glance.url=http://profilarr.${BASE_DOMAIN}/"
      - "glance.description=Custom Format Manager"
      - "traefik.enable=true"
      # - "traefik.http.routers.bazarr.middlewares=authentik@docker"
      - "traefik.http.routers.profilarr.rule=Host(`profilarr.${BASE_DOMAIN}`)"
      - "traefik.http.routers.profilarr.entrypoints=web"
      - "traefik.http.services.profilarr.loadbalancer.server.port=6868"
      - "docker-volume-backup.stop-during-backup=stop"
      - "traefik.http.routers.profilarr.middlewares=tinyauth"
    networks:
      - proxy_network
    restart: unless-stopped
