services:
    pyload-ng:
        image: lscr.io/linuxserver/pyload-ng:latest
        container_name: pyload-ng
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        networks:
            - proxy_network
        labels:
            - "glance.name=Pyload"
            - "glance.icon=sh:pyload"
            - "glance.url=http://pyload.${BASE_DOMAIN}/"
            - "glance.description=Download Manager"
            - "traefik.enable=true"
            - "traefik.http.routers.pyload-ng.rule=Host(`pyload.${BASE_DOMAIN}`)"
            - "traefik.http.routers.pyload-ng.entrypoints=web"
            - "traefik.http.services.pyload-ng.loadbalancer.server.port=8000"
        volumes:
            - ${DOCKER_CONFIG_BASE}/Pyload_Config:/config
            - ${MEDIA_DOWNLOADS_PATH}/pyload:/downloads
        # ports:
        # - 8000:8000
        # - 9666:9666 #optional
        restart: unless-stopped
