# services/qbittorrent.yaml
services:
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:${QBITTORRENT_VERSION}
        container_name: qbittorrent
        network_mode: service:wireguard
        logging:
            driver: loki:latest
            options:
                loki-url: ${LOKI_URL}
                loki-retries: 5
                loki-max-backoff: 1800ms
                loki-timeout: 1s
                keep-file: "true"
                mode: "non-blocking"
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - WEBUI_PORT=8080
            - TORRENTING_PORT=8443
        volumes:
            - ${DOCKER_CONFIG_BASE}/Qbittorrent_Config:/config
            - ${MEDIA_DOWNLOADS_PATH}:/downloads
            - ${MEDIA_LIBRARY_PATH_RAID}:/mnt/Raid/Learn/Bonus
        # ports:
        #     - 6881:6881
        #     - 6881:6881/udp
        labels:
            - "glance.name=qBittorrent"
            - "glance.icon=sh:qbittorrent"
            - "glance.url=http://qbit.${BASE_DOMAIN}/"
            - "glance.description=Torrent Client"
            - "glance.id=qbittorrent"
            - "traefik.enable=true"
            - "traefik.http.routers.qbit.rule=Host(`qbit.${BASE_DOMAIN}`)"
            - "traefik.http.routers.qbit.entrypoints=web"
            - "traefik.http.services.qbit.loadbalancer.server.port=8080"
        depends_on:
            - wireguard
        # networks:
        #     - proxy_network
        restart: unless-stopped
