services:
    sonarr:
        image: lscr.io/linuxserver/sonarr:${SONARR_VERSION}
        container_name: sonarr
        logging:
            driver: loki:latest
            options:
                loki-url: ${LOKI_URL}
                loki-retries: 5
                loki-max-backoff: 1800ms
                loki-timeout: 1s
                keep-file: "true"
                mode: "non-blocking"
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        networks:
            - proxy_network
        volumes:
            - ${DOCKER_CONFIG_BASE}/Sonarr_Config:/config
            - ${MEDIA_LIBRARY_PATH_RAID}:/data
            - ${MEDIA_LIBRARY_PATH_EDISK}:/data1
            - ${MEDIA_DOWNLOADS_PATH}:/downloads
        labels:
            - "glance.name=Sonarr"
            - "glance.icon=sh:sonarr"
            - "glance.url=http://sonarr.${BASE_DOMAIN}/"
            - "glance.description=TV Shows Management"
            - "traefik.enable=true"
            - "traefik.http.routers.sonarr.rule=Host(`sonarr.${BASE_DOMAIN}`)"
            - "traefik.http.routers.sonarr.entrypoints=web"
            - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
        restart: unless-stopped
