services:
    stremio-docker:
        image: tsaridas/stremio-docker:latest
        container_name: stremio-docker
        networks:
            - proxy_network
        environment:
            - NO_CORS=1
            - AUTO_SERVER_URL=1
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_CONFIG_BASE}/Stremio_Config:/root/.stremio-server
        labels:
            - "glance.name=Stremio"
            - "glance.icon=sh:Stremio"
            - "glance.url=http://stremio.${BASE_DOMAIN}/"
            - "glance.description=stremio"
        ports:
            - "8080:8080/tcp"
        restart: unless-stopped
