services:
    watchtower:
        image: ghcr.io/beatkind/watchtower:latest-dev
        container_name: watchtower
        volumes:
            - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
        ports:
            - 2800:8080
        command: --debug --http-api-update --schedule "${WATCHTOWER_SCHEDULE}" --cleanup --http-api-metrics --http-api-periodic-polls # Use variable
        environment:
            - TZ=${TZ}
            - WATCHTOWER_NOTIFICATIONS=shoutrrr
            - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_TELEGRAM_URL}
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL}
            - WATCHTOWER_HTTP_API_METRICS=true
            - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
            - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_API_TOKEN}
        labels:
            - "glance.parent=portainer"
            - "glance.name=updater"
        restart: unless-stopped
