services:
    wireguard:
        image: linuxserver/wireguard
        container_name: wireguard
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=${TZ}
            # - SERVERURL=${VPN_SERVER_URL} #optional
            - SERVERPORT=51820 #optional
            # - PEERS=1 #optional
            - PEERDNS=auto #optional
            - INTERNAL_SUBNET=10.13.13.0 #optional
            - ALLOWEDIPS=0.0.0.0/0 #optional
        networks:
            - proxy_network
        volumes:
            - /mnt/Docker/Docker/Wireguard_Config/config:/config
            # - /usr/src:/usr/src # location of kernel headers
            - /run/current-system/kernel-modules:/lib/modules
        labels:
            - "glance.parent=qbittorrent"
            - "glance.name=wireguard"
        ports:
            - 51820:51820/udp
            - 8443:8443
            - 8443:8443/udp
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "ping", "-c", "1", "8.8.8.8"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 20s
